sqlite3:
  adapter: sqlite3
  database: spec/acts_as_seo_friendly.sqlite3

mysql:
  adapter: mysql2
  hostname: localhost
  username: root
  password:
  database: acts_as_seo_friendly
  charset: utf8

postgresql:
  adapter: postgresql
  hostname: localhost
  username: postgres
  password:
  database: acts_as_seo_friendly
  encoding: utf8
